#!/bin/zsh

gyb="./Vendor/gyb"

function gyb() {
  find $1 -iname '*.gyb' | while read file; do
    target="${file%.gyb}"
    test -f "$target" && rm "$target"
    $gyb -Darg_count=9 --line-directive '' "$file" > $target
  done
}

gyb Sources
gyb Tests
